import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function index() {
  return (

    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <title>Receitas Rápidas</title>
        <meta name="description" content="Generated by create next app" />
        <a rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem Vindos <a href="https://nextjs.org">Receitas Rápidas!</a>
        </h1>
      <div className={styles.grid}>
       <p className={styles.card}>
         <h1 >
          Seja bem vindo <a href='/home'>ao nosso site!</a>
         </h1>

        <p className={styles.description}>
          Get started by editing{' '}
         <p className={styles.subtitle}>
          Aqui você irá desfrutar de <br/>comidas deliciosas.{' '}
          <code className={styles.code}></code>
        </p>
         </p>

        <a href="/home"><button>CLIQUE PARA COZINHAR</button></a>


        </p>
        <Image src="/frango.PNG" alt="Vercel Logo" width={520} height={200} />
        </ div>
      </main>
    </div>

  )
}